### ISSUE TITLE
Leave Message + Slack Integration + Automated Knowledge Base

### ISSUE THREAD

**Issue by evok3d** [Bit-Nation/bitnation-web#6] opened 2016-10-26 14:10 UTC

**Comment by evok3d** [comment] 2016-10-26 14:11
So in short, i say lets forget about the chat function we had, i mean we really dont have the resources at the moment to have someone on stand by answering peoples questions. We can add that later when we do. So my aim was to:
- allow people to leave questions directly on the site with a click of a button -- like the leave a message bar we have now
- have this relayed into slack so we can see it without having to access a third party platform -- thus reducing the work needed to interact.
- from there depending on the question, we can answer them via the email address they provide.
- also tiered of answering the same questions over and over as im sure many of you are too. So this way with the method they describe we can build a knowledge base directly from the response. As mentioned "To answer your question on how to use the questions that customers ask on knowledge base, if your agent feels that the response that he's sending to your customer(on the ticket)is something that should be added to the knowledge base, he can bcc the response to kbase@<your freshdesk account URL>. This would add the response as draft in knowledge base which your agent can edit and publish it directly."

soooooo, if they ask something we have already answered, they can just see it pop up as they type the question they are asking.

**Comment by ETeissonniere** [comment] 2017-07-27 13:47
@evok3d I think you implemented that, so the issue isn't relevant anymore, closing.

**Closed as completed by ETeissonniere** 2017-07-27 13:47 UTC
